SortingProgram: SortingProgram.o Selectionsort.o Sample.o
	gcc -o BinaryTreeManagerProgram BinaryTreeManagerProgram.o BinaryTreeManagerBip.o Sample.o

BinaryTreeManagerProgram.o: BinaryTreeManagerProgram.c
	gcc -c BinaryTreeManagerProgram.c

BinaryTreeManagerBip.o: BinaryTreeManagerBip.c
	gcc -c BinaryTreeManagerBip.c

Sample.o: Sample.c
	gcc -c Sample.c