BinaryTreeManager: BinaryTreeManager.o Sample.o
	g++ -o BinaryTreeManager BinaryTreeManager.o Sample.o

BinaryTreeManager.o: BinaryTreeManager.cpp
	g++ -c BinaryTreeManager.cpp

Sample.o: Sample.cpp
	g++ -c Sample.cpp