SortingProgram: SortingProgram.o Selectionsort.o Sample.o
	gcc -o SortingProgram SortingProgram.o Selectionsort.o Sample.o

SortingProgram.o: SortingProgram.c
	gcc -c SortingProgram.c

Selectionsort.o: Selectionsort.c
	gcc -c Selectionsort.c

Sample.o: Sample.c
	gcc -c Sample.c